# Generated by Django 3.2.3 on 2021-06-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_train_train_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_number',
            field=models.IntegerField(unique=True, verbose_name='train number'),
        ),
    ]
